// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RoyalDragon.Cdn.Models.Entities
{
    public partial class FamilyTreeDbContext : DbContext
    {
        public FamilyTreeDbContext()
        {
        }

        public FamilyTreeDbContext(DbContextOptions<FamilyTreeDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FamilyRelationShip> FamilyRelationShip { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FamilyRelationShip>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Bdate).HasColumnName("bdate");

                entity.Property(e => e.Ddate).HasColumnName("ddate");

                entity.Property(e => e.Fid).HasColumnName("fid");

                entity.Property(e => e.Gender)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("gender");

                entity.Property(e => e.Img)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("img");

                entity.Property(e => e.Mid).HasColumnName("mid");

                entity.Property(e => e.Name)
                    .HasMaxLength(200)
                    .HasColumnName("name");

                entity.Property(e => e.Pids)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("pids");

                entity.Property(e => e.Relationship)
                    .HasMaxLength(200)
                    .HasColumnName("relationship");

                entity.Property(e => e.Tags)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("tags");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.FamilyRelationShip)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_FamilyRelationShip_User");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasIndex(e => e.Username, "UQ__User__536C85E4C784335D")
                    .IsUnique();

                entity.HasIndex(e => e.Email, "UQ__User__A9D105348DF2CC40")
                    .IsUnique();

                entity.Property(e => e.CreateOn)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}