// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace RoyalDragon.Model.ContentDeliveryNetwork.Entities
{
    public partial class ContentDeliveryNetworkContext : DbContext
    {
        public ContentDeliveryNetworkContext()
        {
        }

        public ContentDeliveryNetworkContext(DbContextOptions<ContentDeliveryNetworkContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PublicDocument> PublicDocument { get; set; }
        public virtual DbSet<Ressource> Ressource { get; set; }
        public virtual DbSet<RessourceType> RessourceType { get; set; }
        public virtual DbSet<UserAgentStatistics> UserAgentStatistics { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AI");

            modelBuilder.Entity<PublicDocument>(entity =>
            {
                entity.Property(e => e.Content).IsRequired();

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.Extension)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Label).IsRequired();

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<Ressource>(entity =>
            {
                entity.HasKey(e => e.RessourceId);

                entity.HasIndex(e => e.TypeId, "IX_Ressource_TypeId");

                entity.Property(e => e.Url).HasMaxLength(2000);

                entity.HasOne(d => d.Type)
                    .WithMany(p => p.Ressource)
                    .HasForeignKey(d => d.TypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Ressource_RessourceType");
            });

            modelBuilder.Entity<RessourceType>(entity =>
            {
                entity.HasKey(e => e.TypeId);

                entity.Property(e => e.TypeId).ValueGeneratedNever();

                entity.Property(e => e.Label)
                    .IsRequired()
                    .HasMaxLength(20);
            });

            modelBuilder.Entity<UserAgentStatistics>(entity =>
            {
                entity.HasKey(e => e.UserAgentId)
                    .HasName("PK_AppStatistic_UserAgent");

                entity.HasIndex(e => e.RessourceId, "IX_UserAgentStatistics_RessourceId");

                entity.Property(e => e.Osfamily).HasColumnName("OSFamily");

                entity.Property(e => e.Osmajor).HasColumnName("OSMajor");

                entity.Property(e => e.Osminor).HasColumnName("OSMinor");

                entity.HasOne(d => d.Ressource)
                    .WithMany(p => p.UserAgentStatistics)
                    .HasForeignKey(d => d.RessourceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserAgentStatistics_Ressource");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}