// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.ContentDeliveryNetwork.Entities
{
    public partial class PublicDocument
    {
        public int PublicDocumentId { get; set; }
        public byte[] Content { get; set; }
        public string Label { get; set; }
        public string Extension { get; set; }
        public int? Length { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}