// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.ContentDeliveryNetwork.Entities
{
    public partial class Ressource
    {
        public Ressource()
        {
            UserAgentStatistics = new HashSet<UserAgentStatistics>();
        }

        public int RessourceId { get; set; }
        public Guid Id { get; set; }
        public DateTime? SeenDate { get; set; }
        public DateTime? LastSeenDate { get; set; }
        public string Url { get; set; }
        public int TypeId { get; set; }
        public int? LinkId { get; set; }
        public int? EmployeeId { get; set; }

        public virtual RessourceType Type { get; set; }
        public virtual ICollection<UserAgentStatistics> UserAgentStatistics { get; set; }
    }
}