// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.ContentDeliveryNetwork.Entities
{
    public partial class UserAgentStatistics
    {
        public long UserAgentId { get; set; }
        public int RessourceId { get; set; }
        public string UserAgent { get; set; }
        public string UserAgentFamily { get; set; }
        public string UserAgentMajor { get; set; }
        public string UserAgentMinor { get; set; }
        public string Osfamily { get; set; }
        public string Osmajor { get; set; }
        public string Osminor { get; set; }
        public string DeviceFamily { get; set; }

        public virtual Ressource Ressource { get; set; }
    }
}