// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial class Init_ECommerce_PageResult
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public int PriceOutput { get; set; }
        public string Img { get; set; }
        public int Quantity { get; set; }
        public short SaleOff { get; set; }
        public string BannerImg { get; set; }
        public string IntroduceBannerHtml { get; set; }
        public string Slug { get; set; }
        public int? Star { get; set; }
    }
}
