// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial class InventoryHistory
    {
        public int InventoryHistoryId { get; set; }
        public int InventoryId { get; set; }
        public int PriceInput { get; set; }
        public int PriceOutput { get; set; }
        public int Quantity { get; set; }
        public int CurrentQuantity { get; set; }
        public DateTime CreateOn { get; set; }
        public bool IsActive { get; set; }
        public int CreateByUserId { get; set; }
        public string CreateBy { get; set; }

        public virtual Inventory Inventory { get; set; }
    }
}