// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial class Inventory
    {
        public Inventory()
        {
            InventoryHistory = new HashSet<InventoryHistory>();
        }

        public int InventoryId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public DateTime CreateOn { get; set; }
        public bool IsActive { get; set; }
        public short SaleOff { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<InventoryHistory> InventoryHistory { get; set; }
    }
}