// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RoyalDragon.Admin.Models.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial interface IRoyalDragonDbContextProcedures
    {
        Task<List<Init_ECommerce_PageResult>> Init_ECommerce_PageAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RD_GetProductDetailResult>> RD_GetProductDetailAsync(int? ProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Rd_RegisterAsync(string Username, string Password, string Phone, string Email, string Address, string Birthday, string Fullname, int? RoleId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RD_SettingResult>> RD_SettingAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
