// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial class ProductHistory
    {
        public int ProductHistoryId { get; set; }
        public int ProductId { get; set; }
        public int PriceInput { get; set; }
        public int PriceOutput { get; set; }
        public DateTime CreateOn { get; set; }
        public int CreateByUserId { get; set; }
        public string CreateBy { get; set; }
        public short SaleOff { get; set; }

        public virtual Product Product { get; set; }
    }
}