// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial class ProductOrder
    {
        public int ProductOrderId { get; set; }
        public int PriceInput { get; set; }
        public int PriceOutput { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public short SaleOff { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}