// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Admin.Models.Entities
{
    public partial class User
    {
        public User()
        {
            HistoryCallCustomer = new HashSet<HistoryCallCustomer>();
            Order = new HashSet<Order>();
            UserRole = new HashSet<UserRole>();
        }

        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public DateTime? Birthday { get; set; }
        public bool? IsActive { get; set; }
        public DateTime CreateOn { get; set; }
        public string Fullname { get; set; }
        public string Avatar { get; set; }
        public string Position { get; set; }

        public virtual ICollection<HistoryCallCustomer> HistoryCallCustomer { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}