// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Cdn.Entities
{
    public partial class Category
    {
        public Category()
        {
            Document = new HashSet<Document>();
        }

        public int CategoryId { get; set; }
        public string Label { get; set; }
        public int ApplicationId { get; set; }
        public int CreatedById { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? UpdatedById { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsDisabled { get; set; }
        public int? Rank { get; set; }
        public string Note { get; set; }

        public virtual CmdbParentBusinessServices Application { get; set; }
        public virtual ICollection<Document> Document { get; set; }
    }
}