// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Cdn.Entities
{
    public partial class CmdbParentBusinessServices
    {
        public CmdbParentBusinessServices()
        {
            Category = new HashSet<Category>();
        }

        public int ParentBusinessServiceId { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public int? AppPoolId { get; set; }
        public string Url { get; set; }
        public string Keywords { get; set; }
        public string IconUrl { get; set; }
        public int? DeploymentStatusId { get; set; }
        public int? ApplicationMaturityId { get; set; }
        public string ApplicationDllPath { get; set; }
        public int NbUser { get; set; }
        public int NbPotentialUser { get; set; }
        public int? HomepageCategoryId { get; set; }
        public byte[] IconBinary { get; set; }
        public int? TypeId { get; set; }
        public string CustomStatsController { get; set; }
        public string CustomStatsAction { get; set; }
        public int? RoleReadId { get; set; }
        public int? RoleContributeId { get; set; }
        public int NbMaxDev { get; set; }
        public long? RoleId { get; set; }
        public int? SinglePointOfContactId { get; set; }
        public string Shortcode { get; set; }
        public string VersionExpected { get; set; }
        public int? CreatedById { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedById { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? ConfigurationItemId { get; set; }
        public string Note { get; set; }
        public string Label { get; set; }
        public bool? IsMultibranded { get; set; }
        public string UrlForInte { get; set; }
        public string UrlForQa { get; set; }
        public string UrlForProd { get; set; }
        public string Info { get; set; }
        public bool? IsDisabled { get; set; }
        public int? ParentServicePackageId { get; set; }

        public virtual ICollection<Category> Category { get; set; }
    }
}