// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Cdn.Entities
{
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int PublicDocumentId { get; set; }
        public string Label { get; set; }
        public int CategoryId { get; set; }
        public string Extension { get; set; }
        public int CreatedById { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? UpdatedById { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Category Category { get; set; }
    }
}