// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class BeforeTransaction
    {
        public int BeforeTransactionId { get; set; }
        public double? InputBnb { get; set; }
        public string AddressBuy { get; set; }
        public string Blocknumber { get; set; }
        public string PersonalSign { get; set; }
        public string Nonce { get; set; }
        public string Block { get; set; }
        public string Gas { get; set; }
        public string Gasprice { get; set; }
        public string AddressRef { get; set; }
    }
}