// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class BLC_ActionClaimNftResult
    {
        public string Message { get; set; }
    }
}
