// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class BLC_ListNftOfUserResult
    {
        public int NftUsersId { get; set; }
        public int NftId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public decimal? Bonus { get; set; }
        public DateTime CreateOn { get; set; }
        public string Image { get; set; }
        public int Play { get; set; }
        public int MaxMining { get; set; }
        public int MaxTimeMining { get; set; }
        public int TypeId { get; set; }
        public int UsersId { get; set; }
        public int DayMissionCompleted { get; set; }
        public bool IsStart { get; set; }
        public bool IsActive { get; set; }
    }
}
