// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using RoyalDragon.Model.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RoyalDragon.Model.Models.Entities
{
    public partial interface IBlockChainDbContextProcedures
    {
        Task<List<BLC_ActionClaimNftResult>> BLC_ActionClaimNftAsync(int? UsersId, int? NftId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> BLC_AddAndUpdateRoseAsync(string BlockChainAddress, string BlockChainAddressReferal, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<BLC_GetUsersResult>> BLC_GetUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<BLC_ListNftOfUserResult>> BLC_ListNftOfUserAsync(int? UsersId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
