// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class LogBonusUsers
    {
        public int LogBonusUsersId { get; set; }
        public int UsersId { get; set; }
        public string Ref { get; set; }
        public string FromAddress { get; set; }
        public int Value { get; set; }
        public DateTime CreateOn { get; set; }
    }
}