// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class LogError
    {
        public int LogErrorId { get; set; }
        public string Ex { get; set; }
        public DateTime? CreateOn { get; set; }
    }
}