// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class LogTransaction
    {
        public int LogTransactionId { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public int TransactionCount { get; set; }
        public decimal? Value { get; set; }
        public int TimeStamp { get; set; }
        public int BlockNumber { get; set; }
        public string Hash { get; set; }
        public string Type { get; set; }
        public string AddressRef { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? Sussess { get; set; }
        public string TransactionHashReferal { get; set; }
        public string TransactionHashReceiving { get; set; }
    }
}