// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class Menu
    {
        public int MenuId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public int ParentId { get; set; }
        public bool? IsActive { get; set; }
    }
}