// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class Mp3
    {
        public int Mp3Id { get; set; }
        public string FileName { get; set; }
        public string Name { get; set; }
        public DateTime CreateOn { get; set; }
    }
}