// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class Nft
    {
        public Nft()
        {
            NftUsers = new HashSet<NftUsers>();
        }

        public int NftId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public decimal? Bonus { get; set; }
        public DateTime CreateOn { get; set; }
        public string Image { get; set; }
        public int Play { get; set; }
        public int MaxMining { get; set; }
        public int MaxTimeMining { get; set; }
        public int TypeId { get; set; }
        public double PriceUsdt { get; set; }
        public double PriceBusd { get; set; }
        public string TypeNft { get; set; }

        public virtual ICollection<NftUsers> NftUsers { get; set; }
    }
}