// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class NftUsers
    {
        public NftUsers()
        {
            ClaimedInDay = new HashSet<ClaimedInDay>();
        }

        public int NftUsersId { get; set; }
        public int NftId { get; set; }
        public int UsersId { get; set; }
        public int DayMissionCompleted { get; set; }
        public bool IsStart { get; set; }
        public bool? IsActive { get; set; }
        public DateTime CreateOn { get; set; }

        public virtual Nft Nft { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ClaimedInDay> ClaimedInDay { get; set; }
    }
}