// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class ReceiveTransaction
    {
        public int ReceiveTransactionId { get; set; }
        public string TransactionHash { get; set; }
        public double? Value { get; set; }
        public string FromCustomer { get; set; }
        public string ToOwner { get; set; }
        public int BlockNumber { get; set; }
        public int TransactionIndex { get; set; }
        public int Nonce { get; set; }
        public DateTime CreateOn { get; set; }
        public string Action { get; set; }
    }
}