// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class Settings
    {
        public int SettingsId { get; set; }
        public string ApiKeyBscScan { get; set; }
        public string ContractAddress { get; set; }
        public string AccountReceiveMoney { get; set; }
        public string DefaultPanAbi { get; set; }
        public string PanAbiBnb { get; set; }
        public string AccountPrivateKey { get; set; }
        public int Rate { get; set; }
    }
}