// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class UsersRole
    {
        public int UsersRoleId { get; set; }
        public int RoleId { get; set; }
        public int UsersId { get; set; }

        public virtual Role Role { get; set; }
        public virtual Users Users { get; set; }
    }
}