// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoyalDragon.Model.Models.Entities
{
    public partial class Users
    {
        public Users()
        {
            NftUsers = new HashSet<NftUsers>();
            UsersRole = new HashSet<UsersRole>();
        }

        public int UsersId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Fullname { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public float Balance { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? IsActive { get; set; }
        public string Token { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Youtube { get; set; }
        public string Linkedin { get; set; }
        public string Avatar { get; set; }
        public string PrivateKey { get; set; }
        public string BlockChainAddress { get; set; }
        public string Panabi { get; set; }
        public string ContractAddress { get; set; }
        public string TwoFacode { get; set; }
        public string Refferal { get; set; }
        public string CheckPolicy { get; set; }
        public string Policy { get; set; }
        public string RefferalId { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public int Dona { get; set; }
        public int Level { get; set; }
        public int NftReferal { get; set; }
        public bool IsGetBnbLevel4 { get; set; }
        public double Busd { get; set; }
        public double Bnb { get; set; }
        public double Usdt { get; set; }

        public virtual ICollection<NftUsers> NftUsers { get; set; }
        public virtual ICollection<UsersRole> UsersRole { get; set; }
    }
}